export const LOAN_PRODUCT_TOOLTIPS = {
  name: "The product name identifies this loan product.",
  shortName: "The short name is a compact unique identifier for the loan product.",
  description: "Provide additional information about the purpose and characteristics of this loan product.",
  externalId: "An optional external identifier used to reference this product in another system.",
  fundId: "Assigning a fund identifies the source of funds used for loans created from this product.",
  startDate: "The date from which this loan product becomes active and available to clients.",
  closeDate: "The date after which this loan product becomes inactive and unavailable to clients.",
  includeInBorrowerCycle: "Track how many times a client has taken a loan from this product.",
  isInvoiceDiscounting: "Mark this as an invoice discounting product. Interest is locked at 0% and discounting fees are handled as charges.",

  currencyCode: "The currency in which loans from this product will be disbursed.",
  digitsAfterDecimal: "The number of decimal places used to track and report loan amounts.",
  inMultiplesOf: "Loan amounts are rounded to multiples of this currency value.",
  installmentAmountInMultiplesOf: "Installment amounts are rounded to multiples of this currency value.",

  supportedInterestRefundTypes: "Select transaction types for which interest refunds can be calculated automatically.",

  amortizationType: "Defines how the principal is distributed across the repayment schedule.",
  interestType: "Defines how interest is calculated on the outstanding loan balance.",
  interestCalculationPeriodType: "Controls the period over which interest is calculated, such as daily or per repayment period.",
  transactionProcessingStrategyCode: "Defines how repayments are allocated between principal, interest, fees, and penalties.",
  daysInYearType: "Defines the number of days used when calculating interest for a year.",
  daysInMonthType: "Defines the number of days used when calculating interest for a month.",
  loanScheduleType: "Defines the schedule model used to calculate the loan repayment plan.",
  loanScheduleProcessingType: "Defines how a progressive loan schedule is processed.",
  allowPartialPeriodInterestCalculation: "Allows interest to be calculated for partial periods at the same rate as a full period.",
  isEqualAmortization: "Distributes the amortization amount equally across the repayment periods.",
  graceOnPrincipalPayment: "The number of periods during which principal repayment is deferred.",
  graceOnInterestPayment: "The number of periods during which interest repayment is deferred.",
  graceOnInterestCharged: "The number of periods during which interest is not charged.",
  graceOnArrearsAgeing: "The number of days before an overdue amount starts ageing as arrears.",
  inArrearsTolerance: "The maximum overdue amount allowed before the loan is considered in arrears.",
  overdueDaysForNPA: "The number of overdue days before the account is classified as non-performing.",
  accountMovesOutOfNPAOnlyOnArrearsCompletion: "Keeps the account in NPA status until all arrears have been cleared.",
  multiDisburseLoan: "Enables multiple disbursements, or tranches, for a loan account.",
  maxTrancheCount: "The maximum number of disbursements allowed for one loan account.",
  outstandingLoanBalance: "The maximum outstanding loan balance allowed across the disbursements.",
  disallowExpectedDisbursements: "Prevents expected future disbursements from being included in the loan account.",
  isInterestRecalculationEnabled: "Recalculates interest when repayments or outstanding principal change.",
  preClosureInterestCalculationStrategy: "Defines how interest is calculated when a loan is closed before maturity.",
  rescheduleStrategyMethod: "Defines how advance payments adjust the remaining repayment schedule.",
  interestRecalculationCompoundingMethod: "Defines whether interest, fees, or both are included when recalculating interest.",
  recalculationRestFrequencyType: "Defines how often the outstanding principal is recalculated.",
  recalculationRestFrequencyInterval: "The interval used with the selected outstanding-principal recalculation frequency.",
  isArrearsBasedOnOriginalSchedule: "Calculates arrears against the original repayment schedule instead of the revised schedule.",
  disallowInterestCalculationOnPastDue: "Prevents interest from being calculated on past-due progressive installments.",
  holdGuaranteeFunds: "Reserves guarantee funds against the loan account.",
  mandatoryGuarantee: "The percentage of the loan that must be covered by guarantee funds.",
  minimumGuaranteeFromGuarantor: "The minimum percentage of guarantee funds that must come from a guarantor.",
  minimumGuaranteeFromOwnFunds: "The minimum percentage of guarantee funds that must come from the borrower’s own funds.",
  allowVariableInstallments: "Allows different gaps between installments in the repayment schedule.",
  minimumGap: "The minimum permitted gap between installments.",
  maximumGap: "The maximum permitted gap between installments.",
  enableDownPayment: "Enables a down-payment requirement when the loan is disbursed.",
  disbursedAmountPercentageForDownPayment: "The percentage of the disbursed amount required as a down payment.",
  enableAutoRepaymentForDownPayment: "Automatically posts the down-payment transaction when the loan is disbursed.",
  delinquencyBucketId: "Assigns a delinquency bucket used to track the account’s delinquency status.",
  enableInstallmentLevelDelinquency: "Tracks delinquency separately for each installment.",
  canDefineInstallmentAmount: "Allows a loan officer to define the installment amount when creating a loan account.",
  principalThresholdForLastInstallment: "Merges the remaining principal into the last installment when it falls below this percentage of a regular installment.",
  canUseForTopup: "Allows this loan product to be used for top-up loans.",

  minPrincipal: "The minimum principal amount allowed for this product.",
  principal: "The default principal amount for a loan created from this product.",
  maxPrincipal: "The maximum principal amount allowed for this product.",
  useBorrowerCycle: "Allows principal limits and terms to vary by the borrower’s loan cycle.",
  minNumberOfRepayments: "The minimum number of repayments allowed for this product.",
  numberOfRepayments: "The default number of repayments, excluding any down payment.",
  maxNumberOfRepayments: "The maximum number of repayments allowed for this product.",
  repaymentEvery: "The number of frequency units between scheduled repayments.",
  repaymentFrequencyType: "The time unit used between scheduled repayments, such as days, weeks, or months.",
  minimumDaysBetweenDisbursalAndFirstRepayment: "The minimum number of days between disbursement and the first repayment.",
  repaymentStartDateType: "Defines the date from which the repayment schedule starts.",
  fixedLength: "An optional fixed loan term length in months.",
  isLinkedToFloatingInterestRates: "Links this product’s interest rate to a floating-rate configuration.",
  floatingRatesId: "The floating-rate configuration used to calculate the loan interest rate.",
  minDifferentialLendingRate: "The minimum differential added to the selected floating rate.",
  defaultDifferentialLendingRate: "The default differential added to the selected floating rate.",
  maxDifferentialLendingRate: "The maximum differential added to the selected floating rate.",
  isFloatingInterestRateCalculationAllowed: "Allows the floating rate to be recalculated during the loan term.",
  interestRatePerPeriod: "The default nominal interest rate for each interest-rate period.",
  minInterestRatePerPeriod: "The minimum nominal interest rate allowed for this product.",
  maxInterestRatePerPeriod: "The maximum nominal interest rate allowed for this product.",
  interestRateFrequencyType: "The time unit to which the nominal interest rate applies.",
  interestMethod: "Defines the method used to calculate interest on the loan.",
  allowPartialPeriodInterestCalcualtion: "Allows interest to be calculated for partial periods at the same rate as full periods.",
  allowApprovedDisbursedAmountsOverApplied: "Allows the approved or disbursed amount to exceed the requested amount.",
  overAppliedCalculationType: "Defines how the permitted over-applied amount is calculated.",
  overAppliedNumber: "The amount or percentage allowed above the approved or disbursed amount.",
} as const;
