export interface FineractLoan {
    id: number;
    accountNo: string;
    externalId?: string;
    productId: number;
    productName: string;
    loanProductName?: string;
    shortProductName: string;
    status: {
      id: number;
      code: string;
      value: string;
      active: boolean;
      closed: boolean;
      overpaid?: boolean;
      pendingApproval?: boolean;
      waitingForDisbursal?: boolean;
      closedObligationsMet?: boolean;
      closedWrittenOff?: boolean;
      closedRescheduled?: boolean;
    };
    loanType: {
      id: number;
      code: string;
      value: string;
    };
    loanPurposeId: number;
    currency: {
      code: string;
      name: string;
      decimalPlaces: number;
      inMultiplesOf: number;
      displaySymbol: string;
      nameCode: string;
      displayLabel: string;
    };
    principal: number;
    approvedPrincipal: number;
    proposedPrincipal: number;
    termFrequency: number;
    termPeriodFrequencyType: {
      id: number;
      code: string;
      value: string;
    };
    numberOfRepayments: number;
    repaymentEvery: number;
    interestRatePerPeriod: number;
    interestRateFrequencyType: {
      id: number;
      code: string;
      value: string;
    };
    annualInterestRate: number;
    interestCalculationPeriodType: {
      id: number;
      code: string;
      value: string;
    };
    transactionProcessingStrategy: {
      id: number;
      code: string;
      name: string;
    };
    timeline: {
      submittedOnDate: string | number[];
      submittedByUsername: string;
      submittedByFirstname?: string;
      submittedByLastname?: string;
      approvedOnDate?: string | number[];
      approvedByUsername?: string;
      approvedByFirstname?: string;
      approvedByLastname?: string;
      expectedDisbursementDate?: string | number[];
      actualDisbursementDate?: string | number[];
      disbursedByUsername?: string;
      disbursedByFirstname?: string;
      disbursedByLastname?: string;
      expectedMaturityDate?: string | number[];
      actualMaturityDate?: string | number[];
      closedOnDate?: string | number[];
      closedByUsername?: string;
    };
    summary: {
      principalDisbursed: number;
      principalPaid: number;
      principalOutstanding: number;
      principalOverdue: number;
      principalWrittenOff?: number;
      interestCharged: number;
      interestPaid: number;
      interestOutstanding: number;
      interestOverdue: number;
      interestWaived?: number;
      interestWrittenOff?: number;
      feeChargesCharged: number;
      feeChargesPaid: number;
      feeChargesOutstanding: number;
      feeChargesOverdue: number;
      feeChargesWaived?: number;
      feeChargesWrittenOff?: number;
      penaltyChargesCharged: number;
      penaltyChargesPaid: number;
      penaltyChargesOutstanding: number;
      penaltyChargesOverdue: number;
      penaltyChargesWaived?: number;
      penaltyChargesWrittenOff?: number;
      totalExpectedRepayment: number;
      totalRepayment: number;
      totalOutstanding: number;
      totalOverdue: number;
      totalOverpaid?: number;
      totalWaived?: number;
      totalWrittenOff?: number;
    };
    schedule: {
      currency: {
        code: string;
        name: string;
        decimalPlaces: number;
        inMultiplesOf: number;
        displaySymbol: string;
        nameCode: string;
        displayLabel: string;
      };
      totalPrincipalDisbursed: number;
      totalPrincipalExpected: number;
      totalPrincipalPaid: number;
      totalInterestCharged: number;
      totalFeeChargesCharged: number;
      totalPenaltyChargesCharged: number;
      totalWaived: number;
      totalWrittenOff: number;
      totalRepaymentExpected: number;
      totalRepayment: number;
      totalOutstanding: number;
      period: number;
      loanTermInDays: number;
      totalFeeChargesAtDisbursement: number;
      fixedEmiAmount: number;
      maxOutstandingLoanBalance: number;
      disbursedAmount: number;
      disbursedAmountPercentage: number;
      feeChargesAtDisbursementCharged: number;
      scheduleRegenerated: boolean;
      futureSchedule: any[];
      schedule: any[];
    };
    repaymentSchedule?: {
      currency: {
        code: string;
        name: string;
        decimalPlaces: number;
        inMultiplesOf: number;
        displaySymbol: string;
        nameCode: string;
        displayLabel: string;
      };
      totalPrincipalDisbursed: number;
      totalPrincipalExpected: number;
      totalPrincipalPaid: number;
      totalInterestCharged: number;
      totalInterestPaid: number;
      totalFeeChargesCharged: number;
      totalPenaltyChargesCharged: number;
      totalWaived: number;
      totalWrittenOff: number;
      totalRepaymentExpected: number;
      totalRepayment: number;
      totalOutstanding: number;
      period: number;
      loanTermInDays: number;
      totalFeeChargesAtDisbursement: number;
      fixedEmiAmount: number;
      maxOutstandingLoanBalance: number;
      disbursedAmount: number;
      disbursedAmountPercentage: number;
      feeChargesAtDisbursementCharged: number;
      scheduleRegenerated: boolean;
      futureSchedule: any[];
      periods: Array<{
        period: number;
        fromDate: string | number[];
        dueDate: string | number[];
        obligationsMetOnDate?: string | number[];
        completed: boolean;
        daysInPeriod: number;
        principal: number;
        principalLoanBalanceOutstanding: number;
        interest: number;
        feeCharges: number;
        penaltyCharges: number;
        totalDueForPeriod: number;
        totalPaidForPeriod: number;
        totalInAdvanceForPeriod: number;
        totalOverdue: number;
        outstanding: number;
      }>;
    };
    loanOfficerId: number;
    loanOfficerName: string;
    loanPurposeName: string;
    useInterestRateCharged: boolean;
    syncDisbursementWithMeeting: boolean;
    loanCollateral: any[];
    loanCharge: any[];
    loanCounter: {
      id: number;
      productId: number;
      clientId: number;
      loanId: number;
      loanAccountId: number;
      loanProductName: string;
      loanExternalId: string;
      loanCounterDate: string | number[];
      loanType: {
        id: number;
        code: string;
        value: string;
      };
      loanStatus: {
        id: number;
        code: string;
        value: string;
      };
      loanProductId: number;
    };
    isNPA: boolean;
    daysInMonthType: {
      id: number;
      code: string;
      value: string;
    };
    daysInYearType: {
      id: number;
      code: string;
      value: string;
    };
    interestRecalculationEnabled: boolean;
    createStandingInstructionAtDisbursement: boolean;
    isVariableInstallmentsAllowed: boolean;
    allowVariableInstallments: boolean;
    minimumGap: number;
    maximumGap: number;
    graceOnPrincipalPayment?: number;
    graceOnInterestPayment?: number;
    graceOnArrearsAgeing?: number;
    interestFreePeriod?: number;
    amortizationType: {
      id: number;
      code: string;
      value: string;
    };
    charges: any[];
    collateral: any[];
    multiDisburseLoan: boolean;
    canDefineInstallmentAmount: boolean;
    canUseForTopup: boolean;
    isTopup: boolean;
    closureDate: string | number[];
    inArrears: boolean;
    overdueCharges: any[];
    reschedules?: any[];
    documents?: any[];
    notes?: any[];
    linkedAccount: any;
    canDisburse: boolean;
    emiAmountVariations: any[];
    inArrearsTolerance: number;
    originalLoan: number;
    loanBalance: number;
    amountPaid: number;
    lastRepaymentDate?: string | number[];
    transactions?: any[];
    loanPurpose?: {
      id: number;
      name: string;
    };
    interestType?: {
      id: number;
      code: string;
      value: string;
    };
  }
  