-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "accountNumber" TEXT,
ADD COLUMN     "annualIncome" DOUBLE PRECISION,
ADD COLUMN     "bankName" TEXT,
ADD COLUMN     "collateralType" TEXT,
ADD COLUMN     "collateralValue" DOUBLE PRECISION,
ADD COLUMN     "creditScore" INTEGER,
ADD COLUMN     "employerName" TEXT,
ADD COLUMN     "employmentStatus" TEXT,
ADD COLUMN     "existingLoans" INTEGER DEFAULT 0,
ADD COLUMN     "loanPurpose" TEXT,
ADD COLUMN     "loanTerm" INTEGER,
ADD COLUMN     "monthlyExpenses" DOUBLE PRECISION,
ADD COLUMN     "monthlyIncome" DOUBLE PRECISION,
ADD COLUMN     "requestedAmount" DOUBLE PRECISION,
ADD COLUMN     "riskAssessedBy" TEXT,
ADD COLUMN     "riskAssessmentDate" TIMESTAMP(3),
ADD COLUMN     "riskCategory" TEXT,
ADD COLUMN     "riskFactors" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "riskScore" INTEGER,
ADD COLUMN     "totalDebt" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "yearsEmployed" DOUBLE PRECISION;
